### ISSUE TITLE
Fix support to Diners Club card numbers

### ISSUE THREAD

**Issue by mstred** [jsaa/credit-card-input#1]
I tried using card numbers generated from the following sources and it didn't work for Diners Club:
* https://www.getnewidentity.com/diners-club-credit-card.php
* https://www.brasilnaweb.com.br/blog/cartoes-de-credito-validos-para-teste-de-sistemas
* https://www.4devs.com.br/gerador_de_numero_cartao_credito

**Comment by jsaa** [comment]
Fixed. Thanks!
