### ISSUE TITLE
Improve image size for card logos

### ISSUE THREAD

**Issue by mstred** [jsaa/credit-card-input#2]
Most of the card flag images currently have their size between 10 KB and 30 KB. 

Maybe you could improve that by using smaller pictures and compressing them into a [CSS Sprite](https://css-tricks.com/css-sprites) in order to make them load faster.

Going even further, using [WebP](https://developers.google.com/speed/webp) as an image format could decrease the file size as well.

**Comment by jsaa** [comment]
Fixed
